openapi: 3.2.0
info:
  contact:
    responsibleOrganization: Near Space Labs
  description: Authentication is required for all endpoints and is implemented using OAuth 2.0 with the Client Credentials flow. Users must obtain valid credentials (client ID and secret) to access the service. The authentication system issues Bearer tokens that are valid for 60 minutes, after which they must be refreshed. All requests must include a valid Bearer token in the Authorization header. Failed authentication attempts or expired tokens will result in 401 (Unauthorized) responses, while insufficient permissions will trigger 403 (Forbidden) responses.
  title: Service OAUTH API
  version: 1.0.1
tags:
- name: Oauth
paths:
  /oauth/token:
    post:
      responses:
        '200':
          content:
            application/json:
              examples:
                example1:
                  summary: Example successful response
                  value:
                  - access_token: eyJhbGciO..
                    expires_in: 3600
                    token_type: Bearer
          description: Successful retrieval of access token
        '401':
          content:
            application/json:
              examples:
                example1:
                  summary: Example error response
                  value:
                    error: incorrect NSL_ID or NSL_SECRET
          description: Unauthorized - Invalid client ID or secret
      summary: Retrieve OAuth Token
      requestBody:
        content:
          application/json:
            schema:
              properties:
                audience:
                  description: The target audience for the token "https://api.nearspacelabs.com"
                  example: https://api.nearspacelabs.com
                  type: string
                client_id:
                  description: The client ID for authentication
                  example: your_client_id
                  type: string
                client_secret:
                  description: The client secret for authentication
                  example: your_client_secret
                  type: string
                grant_type:
                  description: Grant type for the token request "client_credentials"
                  example: client_credentials
                  type: string
              required:
              - grant_type
              - audience
              - client_id
              - client_secret
              type: object
        description: Client credentials for authentication
        required: true
      tags:
      - Oauth
